# Usamos una imagen base de Nginx
FROM nginx:alpine

# Copiar archivo de configuración de Nginx a la ubicación estándar de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80
EXPOSE 80

# Ejecutar Nginx en primer plano (sin esto, el contenedor se cerrará inmediatamente)
CMD ["nginx", "-g", "daemon off;"]
