version: '3.8'

services:
  backend:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"

  nginx:
    build: .
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
